
name: 部署文档

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 设置目录
        run: |
        working-directory: rainy

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 设置 pnpm
        working-directory: rainy
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: 设置 Node.js
        working-directory: rainy
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: 安装依赖
        working-directory: rainy
        run: |
          corepack enable
          pnpm install --frozen-lockfile
    

      - name: 构建文档
        working-directory: rainy
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        working-directory: rainy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: rainy/src/.vuepress/dist
